export { claudeDesktop } from './clients/claude-desktop';
export { continueClient } from './clients/continue';
export { cursor } from './clients/cursor';
export { opencode } from './clients/opencode';
export type { ClientAdapter, McpEntry } from './clients/types';
export { zed } from './clients/zed';
export type { LogLevel, McpLogger } from './logger';
export { logger } from './logger';
export type { McpPrompt } from './prompts';
export { getPromptMessages, PROMPTS } from './prompts';
export type { McpResource } from './resources';
export { listResources, readResource } from './resources';
export type { EthosMcpServerConfig } from './server';
export { EthosMcpServer } from './server';
export type { AskPersonalityArgs, AskPersonalityResult } from './tools/ask-personality';
export { askPersonality, askPersonalityToolDef } from './tools/ask-personality';
export { getMessages, getMessagesToolDef } from './tools/get-messages';
export { getSession, getSessionToolDef } from './tools/get-session';
export type { PersonalitySummary } from './tools/list-personalities';
export { listPersonalities, listPersonalitiesToolDef } from './tools/list-personalities';
export { listSessions, listSessionsToolDef } from './tools/list-sessions';
export type { MemorySearchResult } from './tools/search-memory';
export { searchMemory, searchMemoryToolDef } from './tools/search-memory';
export { searchSessions, searchSessionsToolDef } from './tools/search-sessions';
