// When a saved setting takes effect (plan ux-feedback-and-config-clarity B6,
// §6.4–§6.5). One entry per `formName` in `SETTINGS_INDEX` — the completeness
// test (`__tests__/applies-table.test.ts`) fails when the two drift.
//
// HONESTY RULE (§4 B6): a value is upgraded from `'gateway-restart'` only when
// the read path that makes it apply sooner is named in a comment beside it.
// `'gateway-restart'` is the safe claim, not the lazy one: most keys here are
// read once, at wiring time, by whichever process owns them (`ethos gateway
// start`, `ethos serve`, the CLI), and claiming `'live'` without an enforcer
// is exactly the confident-prose failure CLAUDE.md rule 12 documents.
// `'next-turn'` is reserved for keys a per-turn refresh seam demonstrably
// re-reads; no config.yaml key currently qualifies — the per-turn hot-reload
// seams cover personality FILES, not this file.

export type SettingApplies = 'live' | 'next-turn' | 'gateway-restart';

export const SETTING_APPLIES: Readonly<Record<string, SettingApplies>> = {
  // live — gates per RPC call (`requireAdmin`, apps/web-api/src/services/admin.service.ts) and the nav row reads `config.get`
  adminEnabled: 'live',
  apiVersion: 'gateway-restart',
  approvalMode: 'gateway-restart',
  autoCompact: 'gateway-restart',
  'auxCompression.apiKey': 'gateway-restart',
  'auxCompression.baseUrl': 'gateway-restart',
  'auxCompression.model': 'gateway-restart',
  'auxCompression.provider': 'gateway-restart',
  'auxVision.apiKey': 'gateway-restart',
  'auxVision.baseUrl': 'gateway-restart',
  'auxVision.model': 'gateway-restart',
  'auxVision.provider': 'gateway-restart',
  'auxWeb.apiKey': 'gateway-restart',
  'auxWeb.baseUrl': 'gateway-restart',
  'auxWeb.model': 'gateway-restart',
  'auxWeb.provider': 'gateway-restart',
  'background.defaultMaxCostUsd': 'gateway-restart',
  'background.enabled': 'gateway-restart',
  'background.heartbeatMs': 'gateway-restart',
  'background.maxConcurrentJobs': 'gateway-restart',
  'background.maxJobsPerPersonality': 'gateway-restart',
  'background.maxJobsPerRoot': 'gateway-restart',
  'background.maxRootBackgroundUsd': 'gateway-restart',
  'background.queuedTtlMs': 'gateway-restart',
  'background.retentionDays': 'gateway-restart',
  'background.staleMs': 'gateway-restart',
  'backup.cron': 'gateway-restart',
  'backup.dir': 'gateway-restart',
  'backup.enabled': 'gateway-restart',
  'backup.keep': 'gateway-restart',
  'backup.scope': 'gateway-restart',
  'browser.commandTimeoutMs': 'gateway-restart',
  'browser.navigationTimeoutMs': 'gateway-restart',
  callAccent: 'gateway-restart',
  callAccentCustom: 'gateway-restart',
  callStyle: 'gateway-restart',
  'compaction.abortOnSummaryFailure': 'gateway-restart',
  'compaction.gateDelta': 'gateway-restart',
  'compaction.pressure': 'gateway-restart',
  'compaction.retryOnOverflow': 'gateway-restart',
  'compaction.smallWindow': 'gateway-restart',
  'compaction.target': 'gateway-restart',
  contextLayering: 'gateway-restart',
  cronMaxParallelJobs: 'gateway-restart',
  debugMode: 'gateway-restart',
  // live — the drawer reads `config.get` (apps/web/src/App.tsx -> RightDrawer)
  debugPanelEnabled: 'live',
  debugPanelModel: 'gateway-restart',
  'discordMissedMessageBackfill.enabled': 'gateway-restart',
  'discordMissedMessageBackfill.limit': 'gateway-restart',
  'discordMissedMessageBackfill.windowSeconds': 'gateway-restart',
  displayBellOnComplete: 'gateway-restart',
  displayBusyInputMode: 'gateway-restart',
  displayResumeHint: 'gateway-restart',
  displayResumeRecapTurns: 'gateway-restart',
  displayToolPreviewLength: 'gateway-restart',
  displayVerbosity: 'gateway-restart',
  'executionDocker.cpu': 'gateway-restart',
  'executionDocker.diskMb': 'gateway-restart',
  'executionSsh.host': 'gateway-restart',
  'executionSsh.identityFile': 'gateway-restart',
  'executionSsh.knownHostsFile': 'gateway-restart',
  'executionSsh.port': 'gateway-restart',
  'executionSsh.remoteWorkdir': 'gateway-restart',
  'executionSsh.strictHostKeys': 'gateway-restart',
  'executionSsh.user': 'gateway-restart',
  gatewayMaxInboundMediaBytes: 'gateway-restart',
  'kanban.maxInProgress': 'gateway-restart',
  'kanban.maxInProgressPerProfile': 'gateway-restart',
  logsLevel: 'gateway-restart',
  'logsRotation.enabled': 'gateway-restart',
  'logsRotation.maxBytes': 'gateway-restart',
  'logsRotation.maxFiles': 'gateway-restart',
  memory: 'gateway-restart',
  'memoryApproval.cap': 'gateway-restart',
  'memoryApproval.mode': 'gateway-restart',
  'memoryApproval.ttlDays': 'gateway-restart',
  'memoryCapture.apiKey': 'gateway-restart',
  'memoryCapture.baseUrl': 'gateway-restart',
  'memoryCapture.maxPerDay': 'gateway-restart',
  'memoryCapture.maxPerHour': 'gateway-restart',
  'memoryCapture.provider': 'gateway-restart',
  memoryCaptureEnabled: 'gateway-restart',
  memoryCaptureModel: 'gateway-restart',
  'memoryCharLimits.memory': 'gateway-restart',
  'memoryCharLimits.user': 'gateway-restart',
  'memoryConsolidation.exemptUser': 'gateway-restart',
  'memoryConsolidation.flushThreshold': 'gateway-restart',
  'memoryConsolidation.halfLifeDays': 'gateway-restart',
  'memoryConsolidation.maxDeltaChars': 'gateway-restart',
  'memoryConsolidation.maxTokens': 'gateway-restart',
  'memoryConsolidation.minMessagesSinceFlush': 'gateway-restart',
  'memoryConsolidation.threshold': 'gateway-restart',
  'memoryConsolidation.timeboxMs': 'gateway-restart',
  memoryConsolidationEnabled: 'gateway-restart',
  memoryNotices: 'gateway-restart',
  'memoryVault.agentDir': 'gateway-restart',
  'memoryVault.exclude': 'gateway-restart',
  'memoryVault.path': 'gateway-restart',
  'memoryVault.prefetch': 'gateway-restart',
  'modelCatalog.enabled': 'gateway-restart',
  'modelCatalog.ttlHours': 'gateway-restart',
  'modelCatalog.url': 'gateway-restart',
  name: 'gateway-restart',
  'nightlyPass.cron': 'gateway-restart',
  'nightlyPass.enabled': 'gateway-restart',
  origins: 'gateway-restart',
  personality: 'gateway-restart',
  pluginsAutoInstall: 'gateway-restart',
  retentionMinVacuumIntervalDays: 'gateway-restart',
  retentionVacuumAfterPrune: 'gateway-restart',
  scopes: 'gateway-restart',
  // live — the web root re-themes from `config.get` on save (`skinName`, apps/web/src/main.tsx)
  skin: 'live',
  streamingEdits: 'gateway-restart',
  'teamSupervisorRestartLoopGuard.maxRestarts': 'gateway-restart',
  'teamSupervisorRestartLoopGuard.windowSeconds': 'gateway-restart',
  'toolLoop.maxIdenticalToolCallsWarnAt': 'gateway-restart',
  'toolLoop.maxToolCallsWarnAt': 'gateway-restart',
  verbose: 'gateway-restart',
  verbosity: 'gateway-restart',
  voiceApiKey: 'gateway-restart',
  voiceArtifactAbandonAfterDays: 'gateway-restart',
  voiceArtifactMaxTotalMb: 'gateway-restart',
  'voiceBargeIn.browser.energyThreshold': 'gateway-restart',
  'voiceBargeIn.browser.minSpeechMs': 'gateway-restart',
  'voiceBargeIn.browser.silenceMs': 'gateway-restart',
  'voiceBargeIn.call.energyThreshold': 'gateway-restart',
  'voiceBargeIn.call.minSpeechMs': 'gateway-restart',
  'voiceBargeIn.call.silenceMs': 'gateway-restart',
  'voiceBargeIn.satellite.energyThreshold': 'gateway-restart',
  'voiceBargeIn.satellite.minSpeechMs': 'gateway-restart',
  'voiceBargeIn.satellite.silenceMs': 'gateway-restart',
  voiceBaseUrl: 'gateway-restart',
  'voiceChannelTtsOut.discord': 'gateway-restart',
  'voiceChannelTtsOut.email': 'gateway-restart',
  'voiceChannelTtsOut.slack': 'gateway-restart',
  'voiceChannelTtsOut.telegram': 'gateway-restart',
  'voiceChannelTtsOut.whatsapp': 'gateway-restart',
  // live — talk-mode reads `configQuery.data.voiceChime` per call (apps/web/src/pages/Chat.tsx)
  voiceChime: 'live',
  voiceDefaultMode: 'gateway-restart',
  voiceEgressGate: 'gateway-restart',
  voiceEnabled: 'gateway-restart',
  'voiceFiller.afterMs': 'gateway-restart',
  'voiceFiller.enabled': 'gateway-restart',
  'voiceFiller.text': 'gateway-restart',
  'voiceFiller.tickIntervalMs': 'gateway-restart',
  voiceInboundAllowlist: 'gateway-restart',
  voiceInboundConcurrencyCap: 'gateway-restart',
  voiceInboundDailyBudgetUsd: 'gateway-restart',
  voiceInboundOwnerBotKey: 'gateway-restart',
  voiceInboundOwnerChatId: 'gateway-restart',
  voiceInboundOwnerPlatform: 'gateway-restart',
  voiceInboundPerCallerPerHour: 'gateway-restart',
  voiceInboundPrewarm: 'gateway-restart',
  voiceInboundReceptionist: 'gateway-restart',
  voiceLivekitApiKey: 'gateway-restart',
  voiceLivekitApiSecret: 'gateway-restart',
  voiceLivekitUrl: 'gateway-restart',
  voiceModel: 'gateway-restart',
  voiceProvider: 'gateway-restart',
  voiceRealtimeDefault: 'gateway-restart',
  voiceRealtimeSessionBudgetUsd: 'gateway-restart',
  // live — talk-mode reads it from `config.get` per call (apps/web/src/pages/Chat.tsx)
  voiceSpeechMinMs: 'live',
  // live — talk-mode reads it from `config.get` per call (apps/web/src/pages/Chat.tsx)
  voiceSpeechThreshold: 'live',
  voiceSttCommand: 'gateway-restart',
  voiceSttTimeoutMs: 'gateway-restart',
  voiceTier: 'gateway-restart',
  voiceTranscodeBitrateKbps: 'gateway-restart',
  voiceTranscodeFfmpegPath: 'gateway-restart',
  voiceTranscodeTimeoutSec: 'gateway-restart',
  voiceTrunkCodec: 'gateway-restart',
  voiceTrunkFromNumber: 'gateway-restart',
  voiceTrunkId: 'gateway-restart',
  voiceTrunkPassword: 'gateway-restart',
  voiceTrunkProvider: 'gateway-restart',
  voiceTrunkUsername: 'gateway-restart',
  voiceTrunkWebhookPath: 'gateway-restart',
  voiceTrunkWebhookSecret: 'gateway-restart',
  voiceTrustedPlugins: 'gateway-restart',
  voiceTtsApiKey: 'gateway-restart',
  voiceTtsBaseUrl: 'gateway-restart',
  voiceTtsCommand: 'gateway-restart',
  voiceTtsMaxTextLength: 'gateway-restart',
  voiceTtsModel: 'gateway-restart',
  voiceTtsOutputFormat: 'gateway-restart',
  voiceTtsProvider: 'gateway-restart',
  voiceTtsTimeoutMs: 'gateway-restart',
  voiceTtsVoice: 'gateway-restart',
  webBaseUrl: 'gateway-restart',
  webExtractBackend: 'gateway-restart',
  webSearchBackend: 'gateway-restart',
  'weeklyDigest.cron': 'gateway-restart',
  'weeklyDigest.enabled': 'gateway-restart',
  'weeklyDigest.recipients': 'gateway-restart',
};

/** The badge value for a row, or null for a control the index does not name. */
export function appliesForFormName(formName: string): SettingApplies | null {
  return SETTING_APPLIES[formName] ?? null;
}
