import { describe, expect, it } from 'vitest';
import { buildTar, parseTar } from '../backup';
// ---------------------------------------------------------------------------
// Test group 1: Backup archive content
// ---------------------------------------------------------------------------
describe('backup — archive content rules', () => {
    it('includes personality files in subdirectories (skills/)', () => {
        const entries = [
            { relPath: 'personalities/alice/config.yaml', content: Buffer.from('name: alice') },
            { relPath: 'personalities/alice/SOUL.md', content: Buffer.from('# Alice') },
            {
                relPath: 'personalities/alice/skills/code-review.md',
                content: Buffer.from('# Review skill'),
            },
            { relPath: 'personalities/alice/skills/nested/deep.md', content: Buffer.from('# Deep') },
        ];
        const tar = buildTar(entries);
        const parsed = parseTar(tar);
        expect(parsed).toHaveLength(4);
        const paths = parsed.map(([p]) => p);
        expect(paths).toContain('personalities/alice/skills/code-review.md');
        expect(paths).toContain('personalities/alice/skills/nested/deep.md');
    });
    it('does not include keys.json in entries', () => {
        // Verify that if someone accidentally added keys.json it would be present
        // but the backup code is supposed to NOT include it.
        // This is more of a documentation test — the real enforcement is in collectEntries.
        const entries = [
            { relPath: 'config.yaml', content: Buffer.from('provider: anthropic') },
            { relPath: 'MEMORY.md', content: Buffer.from('# Memory') },
        ];
        const tar = buildTar(entries);
        const parsed = parseTar(tar);
        const paths = parsed.map(([p]) => p);
        expect(paths).not.toContain('keys.json');
    });
});
// ---------------------------------------------------------------------------
// Test group 2: MCP token stripping
// ---------------------------------------------------------------------------
describe('backup — MCP token stripping', () => {
    it('MCP token files should not appear in backup entries', () => {
        // Simulating what collectEntries should produce - no access_token/refresh_token/expires_at
        const entries = [
            { relPath: 'personalities/alice/config.yaml', content: Buffer.from('name: alice') },
            {
                relPath: 'personalities/alice/mcp/github/config.yaml',
                content: Buffer.from('url: https://github.com'),
            },
            // These should NOT be in the entries (collectEntries strips them)
        ];
        const tar = buildTar(entries);
        const parsed = parseTar(tar);
        const paths = parsed.map(([p]) => p);
        expect(paths).not.toContain('personalities/alice/mcp/github/access_token');
        expect(paths).not.toContain('personalities/alice/mcp/github/refresh_token');
        expect(paths).not.toContain('personalities/alice/mcp/github/expires_at');
        expect(paths).toContain('personalities/alice/mcp/github/config.yaml');
    });
});
// ---------------------------------------------------------------------------
// Test group 3: secrets.manifest.yaml format
// ---------------------------------------------------------------------------
describe('secrets.manifest.yaml format', () => {
    it('backup manifest includes backed_up_at timestamp', () => {
        const entries = [
            { relPath: 'config.yaml', content: Buffer.from('provider: anthropic') },
            {
                relPath: 'secrets.manifest.yaml',
                content: Buffer.from('# Generated by ethos backup\nbacked_up_at: 2026-05-22T10:00:00Z\n\nglobal:\n  - key: anthropic-api-key\n    fill_with: ethos keys set anthropic-api-key <value>\n'),
            },
        ];
        const tar = buildTar(entries);
        const parsed = parseTar(tar);
        const manifest = parsed.find(([p]) => p === 'secrets.manifest.yaml');
        expect(manifest).toBeDefined();
        if (manifest) {
            const content = manifest[1].toString('utf8');
            expect(content).toContain('backed_up_at:');
            expect(content).toContain('global:');
        }
    });
    it('export manifest includes personality and exported_at', () => {
        const manifestContent = [
            '# Generated by ethos personality export',
            '# Fill these secrets before using this personality',
            'personality: alice',
            'exported_at: 2026-05-22T10:00:00Z',
            '',
            'mcp_auth:',
            '  - server: github',
            '    description: OAuth token for MCP server "github" (stripped from export)',
            '    fill_with: "ethos mcp auth github"',
            '',
        ].join('\n');
        const entries = [
            { relPath: 'personalities/alice/config.yaml', content: Buffer.from('name: alice') },
            { relPath: 'secrets.manifest.yaml', content: Buffer.from(manifestContent) },
        ];
        const tar = buildTar(entries);
        const parsed = parseTar(tar);
        const manifest = parsed.find(([p]) => p === 'secrets.manifest.yaml');
        expect(manifest).toBeDefined();
        if (manifest) {
            const content = manifest[1].toString('utf8');
            expect(content).toContain('personality: alice');
            expect(content).toContain('exported_at:');
            expect(content).toContain('mcp_auth:');
            expect(content).toContain('server: github');
        }
    });
});
// ---------------------------------------------------------------------------
// Test group 4: Personality export exclusions
// ---------------------------------------------------------------------------
describe('personality export — file exclusions', () => {
    it('personal files should not appear in export archive', () => {
        // These are the files that personality export MUST exclude
        const personalFiles = ['MEMORY.md', 'USER.md', 'kanban.db', 'dream-state.json'];
        // A proper export should only have these kinds of entries
        const exportEntries = [
            { relPath: 'personalities/alice/SOUL.md', content: Buffer.from('# I am Alice') },
            { relPath: 'personalities/alice/config.yaml', content: Buffer.from('name: alice') },
            { relPath: 'personalities/alice/toolset.yaml', content: Buffer.from('- read_file') },
            {
                relPath: 'secrets.manifest.yaml',
                content: Buffer.from('personality: alice\nexported_at: 2026-05-22T10:00:00Z\n'),
            },
        ];
        const tar = buildTar(exportEntries);
        const parsed = parseTar(tar);
        const paths = parsed.map(([p]) => p);
        for (const personal of personalFiles) {
            expect(paths).not.toContain(`personalities/alice/${personal}`);
        }
        // But should include the structural files
        expect(paths).toContain('personalities/alice/SOUL.md');
        expect(paths).toContain('personalities/alice/config.yaml');
        expect(paths).toContain('personalities/alice/toolset.yaml');
        expect(paths).toContain('secrets.manifest.yaml');
    });
    it('MCP token files should not appear in export archive', () => {
        const exportEntries = [
            { relPath: 'personalities/alice/config.yaml', content: Buffer.from('name: alice') },
            {
                relPath: 'personalities/alice/mcp/linear/config.yaml',
                content: Buffer.from('url: https://linear.app'),
            },
        ];
        const tar = buildTar(exportEntries);
        const parsed = parseTar(tar);
        const paths = parsed.map(([p]) => p);
        expect(paths).not.toContain('personalities/alice/mcp/linear/access_token');
        expect(paths).not.toContain('personalities/alice/mcp/linear/refresh_token');
        expect(paths).not.toContain('personalities/alice/mcp/linear/expires_at');
        expect(paths).toContain('personalities/alice/mcp/linear/config.yaml');
    });
});
// ---------------------------------------------------------------------------
// Test group 5: Path traversal in personality export archives
// ---------------------------------------------------------------------------
describe('personality export — path traversal defense', () => {
    it('rejects archive entries with ../ path traversal', () => {
        const header = Buffer.alloc(512, 0);
        Buffer.from('personalities/../../../etc/passwd'.padEnd(100, '\0')).copy(header, 0);
        Buffer.from('0000644\0').copy(header, 100);
        Buffer.from('0000000\0').copy(header, 108);
        Buffer.from('0000000\0').copy(header, 116);
        const content = Buffer.from('malicious');
        const sizeOctal = content.length.toString(8).padStart(11, '0');
        Buffer.from(`${sizeOctal}\0`).copy(header, 124);
        Buffer.from('00000000000\0').copy(header, 136);
        header[156] = 0x30;
        Buffer.from('ustar\0').copy(header, 257);
        Buffer.from('00').copy(header, 263);
        let sum = 0;
        for (let i = 0; i < 512; i++)
            sum += header[i] ?? 0;
        Buffer.from(`${sum.toString(8).padStart(6, '0')}\0 `).copy(header, 148);
        const dataBlocks = Math.ceil(content.length / 512);
        const padded = Buffer.alloc(dataBlocks * 512, 0);
        content.copy(padded);
        const end = Buffer.alloc(1024, 0);
        const tar = Buffer.concat([header, padded, end]);
        expect(() => parseTar(tar)).toThrow('Malicious tar entry rejected');
    });
});
// ---------------------------------------------------------------------------
// Test group 6: tar roundtrip with cron/jobs.json
// ---------------------------------------------------------------------------
describe('backup — cron/jobs.json inclusion', () => {
    it('cron/jobs.json roundtrips through tar correctly', () => {
        const cronContent = JSON.stringify([{ name: 'daily', schedule: '0 0 * * *' }]);
        const entries = [
            { relPath: 'config.yaml', content: Buffer.from('provider: anthropic') },
            { relPath: 'cron/jobs.json', content: Buffer.from(cronContent) },
        ];
        const tar = buildTar(entries);
        const parsed = parseTar(tar);
        expect(parsed).toHaveLength(2);
        const cronEntry = parsed.find(([p]) => p === 'cron/jobs.json');
        expect(cronEntry).toBeDefined();
        if (cronEntry) {
            expect(cronEntry[1].toString()).toBe(cronContent);
        }
    });
});
