import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { gunzipSync } from 'node:zlib';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { buildTar, type Entry, parseTar, parseVaultManifest } from '../backup';
import { runPersonalityExport } from '../personality-export';

// ---------------------------------------------------------------------------
// Test group 1: Backup archive content
// ---------------------------------------------------------------------------

describe('backup — archive content rules', () => {
  it('includes personality files in subdirectories (skills/)', () => {
    const entries: Entry[] = [
      { relPath: 'personalities/alice/config.yaml', content: Buffer.from('name: alice') },
      { relPath: 'personalities/alice/SOUL.md', content: Buffer.from('# Alice') },
      {
        relPath: 'personalities/alice/skills/code-review.md',
        content: Buffer.from('# Review skill'),
      },
      { relPath: 'personalities/alice/skills/nested/deep.md', content: Buffer.from('# Deep') },
    ];
    const tar = buildTar(entries);
    const parsed = parseTar(tar);
    expect(parsed).toHaveLength(4);
    const paths = parsed.map(([p]) => p);
    expect(paths).toContain('personalities/alice/skills/code-review.md');
    expect(paths).toContain('personalities/alice/skills/nested/deep.md');
  });

  it('does not include keys.json in entries', () => {
    // Verify that if someone accidentally added keys.json it would be present
    // but the backup code is supposed to NOT include it.
    // This is more of a documentation test — the real enforcement is in collectEntries.
    const entries: Entry[] = [
      { relPath: 'config.yaml', content: Buffer.from('provider: anthropic') },
      { relPath: 'MEMORY.md', content: Buffer.from('# Memory') },
    ];
    const tar = buildTar(entries);
    const parsed = parseTar(tar);
    const paths = parsed.map(([p]) => p);
    expect(paths).not.toContain('keys.json');
  });
});

// ---------------------------------------------------------------------------
// Test group 2: MCP token stripping
// ---------------------------------------------------------------------------

describe('backup — MCP token stripping', () => {
  it('MCP token files should not appear in backup entries', () => {
    // Simulating what collectEntries should produce - no access_token/refresh_token/expires_at
    const entries: Entry[] = [
      { relPath: 'personalities/alice/config.yaml', content: Buffer.from('name: alice') },
      {
        relPath: 'personalities/alice/mcp/github/config.yaml',
        content: Buffer.from('url: https://github.com'),
      },
      // These should NOT be in the entries (collectEntries strips them)
    ];
    const tar = buildTar(entries);
    const parsed = parseTar(tar);
    const paths = parsed.map(([p]) => p);
    expect(paths).not.toContain('personalities/alice/mcp/github/access_token');
    expect(paths).not.toContain('personalities/alice/mcp/github/refresh_token');
    expect(paths).not.toContain('personalities/alice/mcp/github/expires_at');
    expect(paths).toContain('personalities/alice/mcp/github/config.yaml');
  });
});

// ---------------------------------------------------------------------------
// Test group 3: secrets.manifest.yaml format
// ---------------------------------------------------------------------------

describe('secrets.manifest.yaml format', () => {
  it('backup manifest includes backed_up_at timestamp', () => {
    const entries: Entry[] = [
      { relPath: 'config.yaml', content: Buffer.from('provider: anthropic') },
      {
        relPath: 'secrets.manifest.yaml',
        content: Buffer.from(
          '# Generated by ethos backup\nbacked_up_at: 2026-05-22T10:00:00Z\n\nglobal:\n  - key: anthropic-api-key\n    fill_with: ethos keys set anthropic-api-key <value>\n',
        ),
      },
    ];
    const tar = buildTar(entries);
    const parsed = parseTar(tar);
    const manifest = parsed.find(([p]) => p === 'secrets.manifest.yaml');
    expect(manifest).toBeDefined();
    if (manifest) {
      const content = manifest[1].toString('utf8');
      expect(content).toContain('backed_up_at:');
      expect(content).toContain('global:');
    }
  });

  it('export manifest includes personality and exported_at', () => {
    const manifestContent = [
      '# Generated by ethos personality export',
      '# Fill these secrets before using this personality',
      'personality: alice',
      'exported_at: 2026-05-22T10:00:00Z',
      '',
      'mcp_auth:',
      '  - server: github',
      '    description: OAuth token for MCP server "github" (stripped from export)',
      "    fill_with: ethos mcp auth 'github'",
      '',
    ].join('\n');
    const entries: Entry[] = [
      { relPath: 'personalities/alice/config.yaml', content: Buffer.from('name: alice') },
      { relPath: 'secrets.manifest.yaml', content: Buffer.from(manifestContent) },
    ];
    const tar = buildTar(entries);
    const parsed = parseTar(tar);
    const manifest = parsed.find(([p]) => p === 'secrets.manifest.yaml');
    expect(manifest).toBeDefined();
    if (manifest) {
      const content = manifest[1].toString('utf8');
      expect(content).toContain('personality: alice');
      expect(content).toContain('exported_at:');
      expect(content).toContain('mcp_auth:');
      expect(content).toContain('server: github');
    }
  });
});

// ---------------------------------------------------------------------------
// Test group 4: Personality export exclusions
// ---------------------------------------------------------------------------

describe('personality export — file exclusions', () => {
  it('personal files should not appear in export archive', () => {
    // These are the files that personality export MUST exclude
    const personalFiles = ['MEMORY.md', 'USER.md', 'kanban.db', 'dream-state.json'];

    // A proper export should only have these kinds of entries
    const exportEntries: Entry[] = [
      { relPath: 'personalities/alice/SOUL.md', content: Buffer.from('# I am Alice') },
      { relPath: 'personalities/alice/config.yaml', content: Buffer.from('name: alice') },
      { relPath: 'personalities/alice/toolset.yaml', content: Buffer.from('- read_file') },
      {
        relPath: 'secrets.manifest.yaml',
        content: Buffer.from('personality: alice\nexported_at: 2026-05-22T10:00:00Z\n'),
      },
    ];

    const tar = buildTar(exportEntries);
    const parsed = parseTar(tar);
    const paths = parsed.map(([p]) => p);

    for (const personal of personalFiles) {
      expect(paths).not.toContain(`personalities/alice/${personal}`);
    }

    // But should include the structural files
    expect(paths).toContain('personalities/alice/SOUL.md');
    expect(paths).toContain('personalities/alice/config.yaml');
    expect(paths).toContain('personalities/alice/toolset.yaml');
    expect(paths).toContain('secrets.manifest.yaml');
  });

  it('MCP token files should not appear in export archive', () => {
    const exportEntries: Entry[] = [
      { relPath: 'personalities/alice/config.yaml', content: Buffer.from('name: alice') },
      {
        relPath: 'personalities/alice/mcp/linear/config.yaml',
        content: Buffer.from('url: https://linear.app'),
      },
    ];
    const tar = buildTar(exportEntries);
    const parsed = parseTar(tar);
    const paths = parsed.map(([p]) => p);

    expect(paths).not.toContain('personalities/alice/mcp/linear/access_token');
    expect(paths).not.toContain('personalities/alice/mcp/linear/refresh_token');
    expect(paths).not.toContain('personalities/alice/mcp/linear/expires_at');
    expect(paths).toContain('personalities/alice/mcp/linear/config.yaml');
  });
});

// ---------------------------------------------------------------------------
// Test group 5: Path traversal in personality export archives
// ---------------------------------------------------------------------------

describe('personality export — path traversal defense', () => {
  it('rejects archive entries with ../ path traversal', () => {
    const header = Buffer.alloc(512, 0);
    Buffer.from('personalities/../../../etc/passwd'.padEnd(100, '\0')).copy(header, 0);
    Buffer.from('0000644\0').copy(header, 100);
    Buffer.from('0000000\0').copy(header, 108);
    Buffer.from('0000000\0').copy(header, 116);
    const content = Buffer.from('malicious');
    const sizeOctal = content.length.toString(8).padStart(11, '0');
    Buffer.from(`${sizeOctal}\0`).copy(header, 124);
    Buffer.from('00000000000\0').copy(header, 136);
    header[156] = 0x30;
    Buffer.from('ustar\0').copy(header, 257);
    Buffer.from('00').copy(header, 263);
    let sum = 0;
    for (let i = 0; i < 512; i++) sum += header[i] ?? 0;
    Buffer.from(`${sum.toString(8).padStart(6, '0')}\0 `).copy(header, 148);
    const dataBlocks = Math.ceil(content.length / 512);
    const padded = Buffer.alloc(dataBlocks * 512, 0);
    content.copy(padded);
    const end = Buffer.alloc(1024, 0);
    const tar = Buffer.concat([header, padded, end]);

    expect(() => parseTar(tar)).toThrow('Malicious tar entry rejected');
  });
});

// ---------------------------------------------------------------------------
// Test group 6: tar roundtrip with cron/jobs.json
// ---------------------------------------------------------------------------

// Tests archive format only; collectPersonalityEntries is module-private.
describe('personality export — plugins.lock inclusion', () => {
  it('plugins.lock appears in export archive', () => {
    const lockContent = [
      'plugins:',
      '  tools-zerodha:',
      '    package: "@ethos-plugins/tools-zerodha"',
      '    version: "1.4.2"',
      '    registry: "https://registry.npmjs.org"',
      '    integrity: "sha512-abc123"',
      '',
    ].join('\n');

    const entries: Entry[] = [
      { relPath: 'personalities/demo/SOUL.md', content: Buffer.from('# Demo') },
      {
        relPath: 'personalities/demo/config.yaml',
        content: Buffer.from('name: demo\nplugins: tools-zerodha'),
      },
      { relPath: 'personalities/demo/toolset.yaml', content: Buffer.from('- read_file') },
      { relPath: 'personalities/demo/plugins.lock', content: Buffer.from(lockContent) },
    ];

    const tar = buildTar(entries);
    const parsed = parseTar(tar);
    const paths = parsed.map(([p]) => p);
    expect(paths).toContain('personalities/demo/plugins.lock');
  });

  it('plugins.lock roundtrips through tar correctly', () => {
    const lockContent = [
      'plugins:',
      '  my-plugin:',
      '    package: "@ethos-plugins/my-plugin"',
      '    version: "2.0.0"',
      '    registry: "https://npm.corp.internal"',
      '    integrity: "sha512-xyz"',
      '',
    ].join('\n');

    const entries: Entry[] = [
      { relPath: 'personalities/demo/plugins.lock', content: Buffer.from(lockContent) },
    ];
    const tar = buildTar(entries);
    const parsed = parseTar(tar);
    const lockEntry = parsed.find(([p]) => p === 'personalities/demo/plugins.lock');
    expect(lockEntry).toBeDefined();
    if (lockEntry) {
      expect(lockEntry[1].toString()).toBe(lockContent);
    }
  });
});

// ---------------------------------------------------------------------------
// Test group 7: tar roundtrip with cron/jobs.json
// ---------------------------------------------------------------------------

describe('backup — cron/jobs.json inclusion', () => {
  it('cron/jobs.json roundtrips through tar correctly', () => {
    const cronContent = JSON.stringify([{ name: 'daily', schedule: '0 0 * * *' }]);
    const entries: Entry[] = [
      { relPath: 'config.yaml', content: Buffer.from('provider: anthropic') },
      { relPath: 'cron/jobs.json', content: Buffer.from(cronContent) },
    ];
    const tar = buildTar(entries);
    const parsed = parseTar(tar);
    expect(parsed).toHaveLength(2);
    const cronEntry = parsed.find(([p]) => p === 'cron/jobs.json');
    expect(cronEntry).toBeDefined();
    if (cronEntry) {
      expect(cronEntry[1].toString()).toBe(cronContent);
    }
  });
});

// ---------------------------------------------------------------------------
// Test group 8: secrets.manifest.yaml paste lines are shell-quoted
// ---------------------------------------------------------------------------

/**
 * Decode ONE POSIX single-quoted argument back to its literal text, refusing
 * anything a shell would not read as a single word: a character outside the
 * quotes, an unterminated quote, or junk between two quoted runs. A name that
 * survives this round trip cannot have broken out of the quoting.
 */
function decodeSingleQuoted(arg: string): string {
  let text = '';
  let i = 0;
  while (i < arg.length) {
    if (arg[i] !== "'") throw new Error(`unquoted text at ${i}: ${arg}`);
    const close = arg.indexOf("'", i + 1);
    if (close < 0) throw new Error(`unterminated quote: ${arg}`);
    text += arg.slice(i + 1, close);
    i = close + 1;
    if (i < arg.length) {
      if (arg.slice(i, i + 2) !== "\\'") throw new Error(`junk between quotes: ${arg}`);
      text += "'";
      i += 2;
    }
  }
  return text;
}

const argsAfter = (manifest: string, prefix: string): string[] =>
  manifest
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.startsWith(prefix))
    .map((line) => line.slice(prefix.length));

// Every `fill_with:` line in the export manifest exists to be PASTED into a
// terminal. Its argument is a config.yaml field name or an MCP server DIRECTORY
// name — both read off disk verbatim, neither re-checked. Unquoted, one with a
// space produces a broken command and one with `$(…)` or `;` produces a line
// that runs something else entirely.
describe('personality export — secrets manifest paste lines', () => {
  let stateDir: string;
  let prevStateDir: string | undefined;

  beforeEach(async () => {
    stateDir = await mkdtemp(join(tmpdir(), 'ethos-export-quote-'));
    prevStateDir = process.env.ETHOS_STATE_DIR;
    process.env.ETHOS_STATE_DIR = stateDir;
    vi.spyOn(console, 'log').mockImplementation(() => {});
  });

  afterEach(async () => {
    vi.restoreAllMocks();
    if (prevStateDir === undefined) delete process.env.ETHOS_STATE_DIR;
    else process.env.ETHOS_STATE_DIR = prevStateDir;
    await rm(stateDir, { recursive: true, force: true });
  });

  // Field names are lowercased by the config scan; server names are not.
  const FIELDS = ['has space token', 'has;semicolon token', 'has$(id)sub token', "o'brien token"];
  const SERVERS = ['git hub', 'a;rm -rf ~', '$(id)', "o'brien"];

  async function exportManifest(): Promise<string> {
    const dir = join(stateDir, 'personalities', 'demo');
    await mkdir(dir, { recursive: true });
    await writeFile(
      join(dir, 'config.yaml'),
      ['name: Demo', ...FIELDS.map((f) => `${f}: sk-must-never-print`), ''].join('\n'),
    );
    await writeFile(join(dir, 'SOUL.md'), '# Demo\n');
    await writeFile(join(dir, 'toolset.yaml'), '- read_file\n');
    for (const server of SERVERS) {
      await mkdir(join(dir, 'mcp', server), { recursive: true });
      await writeFile(join(dir, 'mcp', server, 'access_token'), 'tok-must-never-print');
    }

    const out = join(stateDir, 'bundle.tar.gz');
    await runPersonalityExport(['demo', '--output', out]);
    const entries = parseTar(gunzipSync(await readFile(out)));
    const manifest = entries.find(([relPath]) => relPath === 'secrets.manifest.yaml');
    if (!manifest) throw new Error('bundle has no secrets.manifest.yaml');
    return manifest[1].toString('utf8');
  }

  it('quotes an unknown secret field so no metacharacter reaches the shell', async () => {
    const manifest = await exportManifest();

    expect(manifest).toContain(`    fill_with: ethos secrets set 'has space token' <value>`);
    expect(manifest).toContain(`    fill_with: ethos secrets set 'has;semicolon token' <value>`);
    expect(manifest).toContain(`    fill_with: ethos secrets set 'has$(id)sub token' <value>`);
    expect(manifest).toContain(`    fill_with: ethos secrets set 'o'\\''brien token' <value>`);

    const args = argsAfter(manifest, 'fill_with: ethos secrets set ').map((rest) =>
      rest.slice(0, rest.lastIndexOf(' <value>')),
    );
    expect(args).toHaveLength(FIELDS.length);
    expect(args.map(decodeSingleQuoted).sort()).toEqual([...FIELDS].sort());
  });

  it('quotes a stripped MCP server name so no metacharacter reaches the shell', async () => {
    const manifest = await exportManifest();

    expect(manifest).toContain(`    fill_with: ethos mcp auth 'git hub'`);
    expect(manifest).toContain(`    fill_with: ethos mcp auth 'a;rm -rf ~'`);
    expect(manifest).toContain(`    fill_with: ethos mcp auth '$(id)'`);
    expect(manifest).toContain(`    fill_with: ethos mcp auth 'o'\\''brien'`);

    const args = argsAfter(manifest, 'fill_with: ethos mcp auth ');
    expect(args).toHaveLength(SERVERS.length);
    expect(args.map(decodeSingleQuoted).sort()).toEqual([...SERVERS].sort());
  });

  // The quoting stops at the command argument. `- key:` and `- server:` are
  // DATA the import path parses back, so they stay verbatim.
  it('leaves the - key: / - server: data fields unquoted and parsing unchanged', async () => {
    const manifest = await exportManifest();

    for (const field of FIELDS) expect(manifest).toContain(`  - key: ${field}\n`);
    for (const server of SERVERS) expect(manifest).toContain(`  - server: ${server}\n`);

    // Round trip through the reader the import path uses: every key comes back
    // byte-identical, and no manifest line leaks a secret value.
    const keys = parseVaultManifest(manifest)
      .map((h) => h.key)
      .filter((k): k is string => k !== undefined);
    expect(keys.sort()).toEqual([...FIELDS].sort());
    expect(manifest).not.toContain('sk-must-never-print');
    expect(manifest).not.toContain('tok-must-never-print');
  });
});

// ---------------------------------------------------------------------------
// Test group 9: plugins.manifest.yaml paste lines are shell-quoted
// ---------------------------------------------------------------------------

// `install:` is the same paste-line class as `fill_with:` above. Its argument is
// either a `plugins:` id out of the personality's config.yaml or a `name` read
// out of a package.json under ~/.ethos/plugins/node_modules — both read off disk
// verbatim, and both travelling in a bundle whoever authored it controls.
//
// plugins.manifest.yaml is DISPLAY ONLY: `runPersonalityImport` never parses it,
// it only lists the filename in `skipFiles` so the file is not written into the
// personality directory. So the quoting changes nothing that is read back, and
// the only thing the line can hurt is the operator who pastes it.
describe('personality export — plugins manifest paste lines', () => {
  let stateDir: string;
  let prevStateDir: string | undefined;

  beforeEach(async () => {
    stateDir = await mkdtemp(join(tmpdir(), 'ethos-export-plugins-quote-'));
    prevStateDir = process.env.ETHOS_STATE_DIR;
    process.env.ETHOS_STATE_DIR = stateDir;
    vi.spyOn(console, 'log').mockImplementation(() => {});
  });

  afterEach(async () => {
    vi.restoreAllMocks();
    if (prevStateDir === undefined) delete process.env.ETHOS_STATE_DIR;
    else process.env.ETHOS_STATE_DIR = prevStateDir;
    await rm(stateDir, { recursive: true, force: true });
  });

  // A `plugins:` id cannot hold a space: the `plugins:` config line is split on
  // whitespace, so a space makes two ids rather than one hostile one. The space
  // case is carried by the package NAME, which comes out of JSON and can hold
  // anything.
  const IDS = ['a;rm', '$(id)', "o'brien"];
  const HOSTILE_PACKAGE = "pkg name;$(id) o'brien";
  const INSTALL_PREFIX = 'install: ethos plugin install ';

  /**
   * Export `demo` and hand back its plugins.manifest.yaml. With no `packages`,
   * ~/.ethos/plugins/node_modules never exists and the export takes the
   * ids-only branch; with packages, it takes the resolved branch for whichever
   * ids a package.json claims and the ids-only fallback for the rest.
   */
  async function exportPluginsManifest(
    packages: Array<{ dir: string; json: Record<string, unknown> }> = [],
  ): Promise<string> {
    const dir = join(stateDir, 'personalities', 'demo');
    await mkdir(dir, { recursive: true });
    await writeFile(join(dir, 'config.yaml'), `name: Demo\nplugins: ${IDS.join(' ')}\n`);
    await writeFile(join(dir, 'SOUL.md'), '# Demo\n');
    await writeFile(join(dir, 'toolset.yaml'), '- read_file\n');

    for (const pkg of packages) {
      const pkgDir = join(stateDir, 'plugins', 'node_modules', pkg.dir);
      await mkdir(pkgDir, { recursive: true });
      await writeFile(join(pkgDir, 'package.json'), JSON.stringify(pkg.json));
    }

    const out = join(stateDir, 'bundle.tar.gz');
    await runPersonalityExport(['demo', '--output', out]);
    const entries = parseTar(gunzipSync(await readFile(out)));
    const manifest = entries.find(([relPath]) => relPath === 'plugins.manifest.yaml');
    if (!manifest) throw new Error('bundle has no plugins.manifest.yaml');
    return manifest[1].toString('utf8');
  }

  it('quotes a plugin id when no plugin is installed to resolve it', async () => {
    const manifest = await exportPluginsManifest();

    expect(manifest).toContain(`    install: ethos plugin install 'a;rm'`);
    expect(manifest).toContain(`    install: ethos plugin install '$(id)'`);
    expect(manifest).toContain(`    install: ethos plugin install 'o'\\''brien'`);

    const args = argsAfter(manifest, INSTALL_PREFIX);
    expect(args).toHaveLength(IDS.length);
    expect(args.map(decodeSingleQuoted).sort()).toEqual([...IDS].sort());
  });

  it('quotes a resolved package name, and the id when nothing resolves it', async () => {
    const manifest = await exportPluginsManifest([
      {
        dir: 'hostile-plugin',
        json: { name: HOSTILE_PACKAGE, version: '1.2.3', ethos: { id: 'a;rm' } },
      },
    ]);

    expect(manifest).toContain(`    install: ethos plugin install 'pkg name;$(id) o'\\''brien'`);

    const args = argsAfter(manifest, INSTALL_PREFIX);
    expect(args).toHaveLength(IDS.length);
    expect(args.map(decodeSingleQuoted).sort()).toEqual(
      [HOSTILE_PACKAGE, '$(id)', "o'brien"].sort(),
    );
  });

  // The quoting stops at the command argument. `- id:`, `package:` and
  // `version:` are data lines, not commands, and stay exactly as they were.
  it('leaves the - id: / package: / version: data fields unquoted', async () => {
    const manifest = await exportPluginsManifest([
      {
        dir: 'hostile-plugin',
        json: { name: HOSTILE_PACKAGE, version: '1.2.3', ethos: { id: 'a;rm' } },
      },
    ]);

    for (const id of IDS) expect(manifest).toContain(`  - id: ${id}\n`);
    expect(manifest).toContain(`    package: "${HOSTILE_PACKAGE}"\n`);
    expect(manifest).toContain('    version: "1.2.3"\n');
    // Never a double-quoted YAML string wrapping the command: `\'` is not a
    // YAML escape, so `"… '\''…"` would not parse.
    expect(manifest).not.toContain('install: "ethos plugin install');
  });
});

// ---------------------------------------------------------------------------
// Test group 10: a newline is not a shell problem — it is a FORMAT problem
// ---------------------------------------------------------------------------
//
// Single-quoting stops a metacharacter breaking out WITHIN a line and does
// nothing about a newline, which does not break out of the shell at all: it
// breaks out of the manifest. A name carrying one writes NEW lines — another
// `fill_with:`/`install:` the operator is told to paste, another `- key:` /
// `- server:` the import path parses back as data. Both files here are built by
// string concatenation from names read off disk verbatim.
describe('personality export — a name that would split a manifest is refused', () => {
  let stateDir: string;
  let prevStateDir: string | undefined;

  beforeEach(async () => {
    stateDir = await mkdtemp(join(tmpdir(), 'ethos-export-split-'));
    prevStateDir = process.env.ETHOS_STATE_DIR;
    process.env.ETHOS_STATE_DIR = stateDir;
    vi.spyOn(console, 'log').mockImplementation(() => {});
  });

  afterEach(async () => {
    vi.restoreAllMocks();
    if (prevStateDir === undefined) delete process.env.ETHOS_STATE_DIR;
    else process.env.ETHOS_STATE_DIR = prevStateDir;
    await rm(stateDir, { recursive: true, force: true });
  });

  /**
   * Everything that is NOT a comment. The refusal notice names the refused
   * string (escaped, on one line) on purpose, so a bare `toContain` would see
   * it; what must not exist is a forged line a READER would take as data.
   */
  const dataLines = (manifest: string): string =>
    manifest
      .split('\n')
      .filter((l) => !l.trimStart().startsWith('#'))
      .join('\n');

  /** `\n` is the only control character a manifest may contain. */
  // biome-ignore lint/suspicious/noControlCharactersInRegex: finding them is the point
  const RAW_CONTROL = /[\u0000-\u0009\u000b-\u001f\u007f]/;

  async function seed(configLines: string[]): Promise<string> {
    const dir = join(stateDir, 'personalities', 'demo');
    await mkdir(dir, { recursive: true });
    await writeFile(join(dir, 'config.yaml'), `${['name: Demo', ...configLines, ''].join('\n')}`);
    await writeFile(join(dir, 'SOUL.md'), '# Demo\n');
    await writeFile(join(dir, 'toolset.yaml'), '- read_file\n');
    return dir;
  }

  async function exportAndRead(name: string): Promise<string | undefined> {
    const out = join(stateDir, 'bundle.tar.gz');
    await runPersonalityExport(['demo', '--output', out]);
    const entries = parseTar(gunzipSync(await readFile(out)));
    return entries.find(([relPath]) => relPath === name)?.[1].toString('utf8');
  }

  // A config.yaml field name cannot hold an LF — the scan splits the file on
  // `\n` first — but it can hold a CR, and CR is a line terminator to a real
  // YAML reader and to anything that trims a line's end.
  it('leaves out a secret field name carrying a carriage return', async () => {
    await seed(['clean_token: sk-must-never-print', 'evil\r  - key: PWNED_token: x']);

    const manifest = await exportAndRead('secrets.manifest.yaml');
    expect(manifest).toBeDefined();
    if (!manifest) return;

    expect(dataLines(manifest)).not.toContain('PWNED');
    expect(manifest).not.toMatch(RAW_CONTROL);
    expect(manifest).toContain('  - key: clean_token');
    expect(manifest).toContain('# ⚠ 1 name(s) REFUSED');
    expect(manifest).toContain('\\u000d');
    // The reader the import path uses sees exactly the one real key.
    expect(
      parseVaultManifest(manifest)
        .map((h) => h.key)
        .filter((k) => k !== undefined),
    ).toEqual(['clean_token']);
    expect(manifest).not.toContain('sk-must-never-print');
  });

  // MCP server names are DIRECTORY names, and Unix permits a newline in one.
  it('leaves out an MCP server directory name carrying a newline', async () => {
    const dir = await seed([]);
    for (const server of ['github', 'evil\n  - server: PWNED']) {
      await mkdir(join(dir, 'mcp', server), { recursive: true });
      await writeFile(join(dir, 'mcp', server, 'access_token'), 'tok-must-never-print');
    }

    const manifest = await exportAndRead('secrets.manifest.yaml');
    expect(manifest).toBeDefined();
    if (!manifest) return;

    expect(dataLines(manifest)).not.toContain('PWNED');
    expect(manifest).not.toMatch(RAW_CONTROL);
    expect(manifest).toContain('  - server: github');
    expect(manifest).toContain('# ⚠ 1 name(s) REFUSED');
    expect(manifest).toContain('\\u000a');
    expect(
      dataLines(manifest)
        .split('\n')
        .filter((l) => l.includes('- server:')),
    ).toHaveLength(1);
    expect(manifest).not.toContain('tok-must-never-print');
  });

  // `name` and `version` come out of a bundled package.json, so unlike an id
  // off a whitespace-split config line they really can hold a literal newline.
  it('falls back to the id when a resolved package NAME carries a newline', async () => {
    await seed(['plugins: acme']);
    const pkgDir = join(stateDir, 'plugins', 'node_modules', 'acme');
    await mkdir(pkgDir, { recursive: true });
    await writeFile(
      join(pkgDir, 'package.json'),
      JSON.stringify({
        name: 'acme\n    install: ethos plugin install PWNED',
        version: '1.2.3',
        ethos: { id: 'acme' },
      }),
    );

    const manifest = await exportAndRead('plugins.manifest.yaml');
    expect(manifest).toBeDefined();
    if (!manifest) return;

    expect(dataLines(manifest)).not.toContain('PWNED');
    expect(manifest).not.toMatch(RAW_CONTROL);
    // The plugin is still named and still installable, by its id.
    expect(manifest).toContain('  - id: acme');
    expect(manifest).toContain(`    install: ethos plugin install 'acme'\n`);
    expect(manifest).not.toContain('    package:');
    expect(manifest).toContain('# ⚠ 1 name(s) REFUSED');
  });

  it('falls back to the id when a resolved package VERSION carries a newline', async () => {
    await seed(['plugins: acme']);
    const pkgDir = join(stateDir, 'plugins', 'node_modules', 'acme');
    await mkdir(pkgDir, { recursive: true });
    await writeFile(
      join(pkgDir, 'package.json'),
      JSON.stringify({
        name: 'acme',
        version: '1.2.3"\n    install: ethos plugin install PWNED',
        ethos: { id: 'acme' },
      }),
    );

    const manifest = await exportAndRead('plugins.manifest.yaml');
    expect(manifest).toBeDefined();
    if (!manifest) return;

    expect(dataLines(manifest)).not.toContain('PWNED');
    expect(manifest).not.toMatch(RAW_CONTROL);
    expect(manifest).toContain('  - id: acme');
    expect(manifest).not.toContain('    version:');
    expect(manifest).toContain('# ⚠ 1 name(s) REFUSED');
  });

  // `\s+` already drops CR and LF from an id, but not the rest of the C0
  // range, so an id still reaches the emitter carrying something a YAML
  // reader would choke on and a terminal would swallow.
  it('leaves out a plugin id carrying a control character', async () => {
    await seed([`plugins: clean evil${String.fromCharCode(1)}x`]);

    const manifest = await exportAndRead('plugins.manifest.yaml');
    expect(manifest).toBeDefined();
    if (!manifest) return;

    expect(manifest).not.toMatch(RAW_CONTROL);
    expect(manifest).toContain('  - id: clean');
    expect(manifest).not.toContain('  - id: evil');
    expect(manifest).toContain('# ⚠ 1 name(s) REFUSED');
    expect(manifest).toContain('\\u0001');
  });
});

// A known secret field's paste line must name the vault ref the runtime reads
// (`secretRefForConfigKey`, the same one setup writes and `ethos doctor`
// checks), not the `anthropic-api-key`-style refs nothing reads.
describe('personality export — known secret fields name the real vault ref', () => {
  let stateDir: string;
  let prevStateDir: string | undefined;

  beforeEach(async () => {
    stateDir = await mkdtemp(join(tmpdir(), 'ethos-export-refs-'));
    prevStateDir = process.env.ETHOS_STATE_DIR;
    process.env.ETHOS_STATE_DIR = stateDir;
    vi.spyOn(console, 'log').mockImplementation(() => {});
  });

  afterEach(async () => {
    vi.restoreAllMocks();
    if (prevStateDir === undefined) delete process.env.ETHOS_STATE_DIR;
    else process.env.ETHOS_STATE_DIR = prevStateDir;
    await rm(stateDir, { recursive: true, force: true });
  });

  it('points each known field at the ref setup writes', async () => {
    const dir = join(stateDir, 'personalities', 'demo');
    await mkdir(dir, { recursive: true });
    const fields = [
      'anthropicApiKey',
      'openaiApiKey',
      'telegramToken',
      'discordToken',
      'slackBotToken',
      'slackAppToken',
      'slackSigningSecret',
      'emailPassword',
    ];
    await writeFile(
      join(dir, 'config.yaml'),
      ['name: Demo', ...fields.map((f) => `${f}: never-exported`), ''].join('\n'),
    );
    await writeFile(join(dir, 'SOUL.md'), '# Demo\n');
    await writeFile(join(dir, 'toolset.yaml'), '- read_file\n');

    const out = join(stateDir, 'bundle.tar.gz');
    await runPersonalityExport(['demo', '--output', out]);
    const manifest = parseTar(gunzipSync(await readFile(out)))
      .find(([relPath]) => relPath === 'secrets.manifest.yaml')?.[1]
      .toString('utf8');
    if (!manifest) throw new Error('bundle has no secrets.manifest.yaml');

    expect(argsAfter(manifest, 'fill_with: ')).toEqual([
      'ethos secrets set providers/anthropic/apiKey <value>',
      'ethos secrets set providers/openai/apiKey <value>',
      'ethos secrets set telegram/token <value>',
      'ethos secrets set discord/token <value>',
      'ethos secrets set slack/botToken <value>',
      'ethos secrets set slack/appToken <value>',
      'ethos secrets set slack/signingSecret <value>',
      'ethos secrets set email/password <value>',
    ]);
    expect(manifest).not.toContain('ethos keys set');
    expect(manifest).not.toContain('never-exported');
  });
});
