import type { ConfigGetData } from '../lib/config-types';

/** Every field `ConfigGetOutput` (`packages/web-contracts/src/router.ts`)
 *  declares, defaulted the way an unconfigured deployment reads. Mechanical,
 *  not hand-picked — each value is the schema's own "unset" shape (`null` for
 *  every `.nullable()` scalar, `{}` / `[]` for every record / array).
 *  Extracted from `settings-callouts.test.ts` so the version-skew test
 *  (`settings-resolved-skew.test.ts`) can mount `SettingsShell` on the same
 *  complete shape. */
export function configGetFixture(): ConfigGetData {
  return {
    provider: 'anthropic',
    model: 'claude-opus-4-7',
    apiKeyPreview: 'sk-…abc1',
    baseUrl: null,
    resolved: {
      stateDir: '/data',
      configPath: '/data/config.yaml',
      personality: { id: 'researcher', source: 'personality' },
      model: { id: 'claude-opus-4-7', rung: 'model:' },
      apiKey: { provider: 'anthropic', source: 'vault', ref: 'providers/anthropic/apiKey' },
      warnings: [],
    },
    personality: 'researcher',
    memory: 'markdown',
    modelRouting: {},
    skin: 'default',
    providers: [],
    providersVersion: 'v0',
    providersNotices: [],
    approvalMode: 'manual',
    verbosity: 'balanced',
    debugMode: false,
    contextLayering: false,
    debugPanelEnabled: false,
    debugPanelModel: null,
    adminEnabled: false,
    streamingEdits: 'off',
    callStyle: 'personality',
    callAccent: 'personality',
    autoCompact: true,
    memoryConsolidationEnabled: false,
    memoryCaptureEnabled: false,
    memoryCaptureModel: null,
    memoryNotices: true,
    voiceChime: true,
    voiceEndpointSilenceMs: 700,
    voiceBargeThreshold: 0.06,
    voiceBargeSustainMs: 250,
    voiceSpeechThreshold: 0.02,
    voiceSpeechMinMs: 150,
    voiceProvider: null,
    voiceApiKeyPreview: null,
    voiceBaseUrl: null,
    voiceModel: null,
    voiceTtsProvider: null,
    voiceTtsApiKeyPreview: null,
    voiceTtsVoice: null,
    voiceTtsBaseUrl: null,
    voiceTtsModel: null,
    voiceSttCommand: null,
    voiceTtsCommand: null,
    voiceTtsOutputFormat: null,
    voiceTtsTimeoutMs: null,
    voiceTtsMaxTextLength: null,
    voiceSttTimeoutMs: null,
    voiceTrustedPlugins: null,
    voiceDefaultMode: null,
    voiceChannelTtsOut: {},
    voiceTranscodeFfmpegPath: null,
    voiceTranscodeBitrateKbps: null,
    voiceTranscodeTimeoutSec: null,
    voiceArtifactAbandonAfterDays: null,
    voiceArtifactMaxTotalMb: null,
    voiceTtsProviders: {},
    voiceSttProviders: {},
    voiceRealtimeProviders: {},
    voiceRealtimeDefault: null,
    voiceTier: null,
    voiceRealtimeSessionBudgetUsd: null,
    voiceTrunkProvider: null,
    voiceTrunkId: null,
    voiceTrunkFromNumber: null,
    voiceTrunkUsername: null,
    voiceTrunkPasswordPreview: null,
    voiceTrunkWebhookSecretPreview: null,
    voiceTrunkWebhookPath: null,
    voiceTrunkCodec: null,
    voiceLivekitUrl: null,
    voiceLivekitApiKeyPreview: null,
    voiceLivekitApiSecretPreview: null,
    voiceInboundAllowlist: null,
    voiceInboundReceptionist: null,
    voiceInboundConcurrencyCap: null,
    voiceInboundPerCallerPerHour: null,
    voiceInboundDailyBudgetUsd: null,
    voiceInboundPrewarm: null,
    voiceInboundOwnerPlatform: null,
    voiceInboundOwnerChatId: null,
    voiceInboundOwnerBotKey: null,
    voiceBargeIn: {},
    voiceBots: [],
    apiVersion: null,
    verbose: false,
    displayVerbosity: 'default',
    displayBusyInputMode: 'interrupt',
    displayToolPreviewLength: 0,
    displayResumeHint: true,
    displayResumeRecapTurns: 3,
    displayBellOnComplete: false,
    compaction: {
      pressure: null,
      target: null,
      gateDelta: null,
      retryOnOverflow: true,
      abortOnSummaryFailure: false,
      smallWindow: 'auto',
    },
    voiceFiller: { enabled: true, afterMs: null, text: null, tickIntervalMs: null },
    memoryVault: { path: null, agentDir: null, prefetch: [], exclude: [] },
    memoryApproval: { mode: 'off', cap: 200, ttlDays: 30 },
    memoryConsolidation: {
      halfLifeDays: 30,
      threshold: 0.05,
      exemptUser: true,
      flushThreshold: 0.7,
      timeboxMs: 30000,
      maxTokens: 1024,
      maxDeltaChars: 4000,
      minMessagesSinceFlush: 8,
    },
    memoryCapture: {
      provider: null,
      apiKeyPreview: null,
      baseUrl: null,
      maxPerHour: 6,
      maxPerDay: 30,
    },
    background: {
      enabled: false,
      maxConcurrentJobs: 2,
      maxJobsPerRoot: 3,
      maxJobsPerPersonality: 5,
      defaultMaxCostUsd: 1,
      maxRootBackgroundUsd: 5,
      queuedTtlMs: 900000,
      staleMs: 90000,
      heartbeatMs: 30000,
      retentionDays: 30,
    },
    retention: {},
    personalityRetention: {},
    webhooks: {},
    quickCommands: {},
    channelToolsets: {},
    backup: { enabled: true, cron: null, scope: [], keep: null, dir: null },
    nightlyPass: { enabled: false, cron: '0 3 * * *' },
    weeklyDigest: { enabled: false, cron: '0 9 * * 1', recipients: [] },
    modelCatalog: { enabled: true, url: null, ttlHours: 24 },
    logsRotation: { enabled: true, maxBytes: null, maxFiles: null },
    webSearchBackend: null,
    webExtractBackend: null,
    webSearxngUrl: null,
    auxCompression: { model: null, provider: null, apiKeyPreview: null, baseUrl: null },
    auxVision: { model: null, provider: null, apiKeyPreview: null, baseUrl: null },
    auxWeb: { model: null, provider: null, apiKeyPreview: null, baseUrl: null },
    a2aEnabled: false,
    pluginsAutoInstall: null,
    webBaseUrl: null,
    retentionVacuumAfterPrune: false,
    retentionMinVacuumIntervalDays: null,
    logsLevel: 'debug',
    memoryCharLimits: { memory: 524_288, user: 524_288 },
    executionDocker: { cpu: 2, diskMb: null },
    executionSsh: {
      host: null,
      user: null,
      port: null,
      identityFile: null,
      knownHostsFile: null,
      strictHostKeys: null,
      remoteWorkdir: null,
    },
    kanban: { maxInProgress: null, maxInProgressPerProfile: null },
    cronMaxParallelJobs: null,
    toolLoop: { maxToolCallsWarnAt: null, maxIdenticalToolCallsWarnAt: null },
    browser: {
      navigationTimeoutMs: 30_000,
      commandTimeoutMs: 10_000,
      headed: 'auto',
      idleTimeoutMs: 600_000,
      stealthEnabled: false,
      profilesEnabled: false,
      proxyServer: null,
      proxyUsername: null,
      proxyPasswordPreview: null,
    },
    gatewayMaxInboundMediaBytes: null,
    teamSupervisorRestartLoopGuard: { maxRestarts: 5, windowSeconds: 60 },
    discordMissedMessageBackfill: { enabled: true, windowSeconds: null, limit: 50 },
  };
}
