import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting started',
      collapsed: false,
      items: [
        'getting-started/what-is-ethos',
        'getting-started/architecture-90-seconds',
        'getting-started/why-ethos',
        'getting-started/glossary',
      ],
    },
    {
      type: 'category',
      label: 'Using Ethos',
      collapsed: false,
      items: [
        'using/quickstart',
        {
          type: 'category',
          label: 'Tutorials',
          collapsed: true,
          items: [
            'using/tutorials/first-agent',
            'using/tutorials/first-personality',
            'using/tutorials/first-deploy-telegram',
          ],
        },
        {
          type: 'category',
          label: 'How-to',
          collapsed: true,
          items: [
            'using/how-to/configure-providers',
            'using/how-to/deploy-in-production',
            'using/how-to/deploy-on-ec2',
            'using/how-to/run-multiple-bots',
            'using/how-to/run-as-daemon',
            'using/how-to/run-in-docker',
            'using/how-to/use-skills',
            'using/how-to/migrate-from-openclaw',
            'using/how-to/use-as-mcp-server',
            'using/how-to/set-up-approval-gates',
            'using/how-to/run-a-team-with-kanban',
            'using/how-to/use-team-memory',
            'using/how-to/receive-files-via-telegram',
            'using/how-to/receive-files-via-slack',
            'using/how-to/send-cross-channel-messages',
            'using/how-to/use-chatgpt-subscription-via-codex',
          ],
        },
        {
          type: 'category',
          label: 'Reference',
          collapsed: true,
          items: [
            'using/reference/cli',
            'using/reference/config-yaml',
            'using/reference/mcp-config',
            'using/reference/messaging-json',
            'using/reference/personality-yaml',
            'using/reference/slash-commands',
          ],
        },
        {
          type: 'category',
          label: 'Explanation',
          collapsed: true,
          items: [
            'using/explanation/what-is-a-personality',
            'using/explanation/built-in-personalities',
            'using/explanation/what-is-a-skill',
            'using/explanation/memory-model',
            'using/explanation/sessions-and-history',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Building on Ethos',
      collapsed: false,
      items: [
        'building/quickstart',
        {
          type: 'category',
          label: 'Tutorials',
          collapsed: true,
          items: [
            'building/tutorials/write-your-first-tool',
            'building/tutorials/first-custom-tool-with-capabilities',
            'building/tutorials/add-an-llm-provider',
            'building/tutorials/add-a-channel-adapter',
            'building/tutorials/first-mission-control',
            'building/tutorials/build-custom-dashboard',
          ],
        },
        {
          type: 'category',
          label: 'How-to',
          collapsed: true,
          items: [
            'building/how-to/publish-a-plugin',
            'building/how-to/write-an-llm-provider-plugin',
            'building/how-to/write-a-memory-backend-plugin',
            'building/how-to/add-a-memory-provider',
            'building/how-to/add-a-hook',
            'building/how-to/add-a-skill',
            'building/how-to/add-a-filesystem-tool',
            'building/how-to/add-a-network-tool',
            'building/how-to/add-a-stateful-tool',
            'building/how-to/point-sdk-at-ethos',
            'building/how-to/openai-server-chat',
            'building/how-to/add-a-panel',
            'building/how-to/display-live-tool-events',
            'building/how-to/authenticate-dashboard-users',
            'building/how-to/build-a-python-client',
            'building/how-to/migrate-cookie-to-api-key',
            'building/how-to/deploy-mission-control-remote',
            'building/how-to/consume-attachments-in-a-tool',
          ],
        },
        {
          type: 'category',
          label: 'Reference',
          collapsed: true,
          items: [
            'building/reference/agent-event',
            'building/reference/tool-interface',
            'building/reference/llm-provider-interface',
            'building/reference/hook-registry',
            'building/reference/tool-registry',
            'building/reference/storage-interface',
            'building/reference/plugin-sdk',
            'building/reference/personality-registry',
            'building/reference/kanban-tools',
            'building/reference/team-tools',
            'building/reference/image-tools',
            'building/reference/vision-tools',
            'building/reference/browser-tools',
            'building/reference/tts-tools',
            'building/reference/messaging-tools',
            'building/reference/skills-tools',
            'building/reference/cron-tools',
            'building/reference/sdk-client',
            'building/reference/sdk-event-stream',
            'building/reference/stability-tier-table',
            'building/reference/api-key-scopes',
            'building/reference/service-coupling-audit',
            'building/reference/model-catalog',
          ],
        },
        {
          type: 'category',
          label: 'Explanation',
          collapsed: true,
          items: [
            'building/explanation/personality-as-architecture',
            'building/explanation/personality-governance',
            'building/explanation/tool-shape',
            'building/explanation/injection-at-construction',
            'building/explanation/hook-execution-models',
            'building/explanation/tool-result-budget',
            'building/explanation/context-cost-optimization',
            'building/explanation/audience-boundary',
            'building/explanation/teams-and-meshes',
            'building/explanation/why-orpc',
            'building/explanation/personality-from-outside',
            'building/explanation/sdk-memory-model',
            'building/explanation/stability-tiers',
            'building/explanation/transport-seam',
            'building/explanation/why-attachments-are-a-capability',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Platforms',
      collapsed: true,
      items: ['platforms/cli', 'platforms/telegram', 'platforms/discord', 'platforms/slack'],
    },
    {
      type: 'category',
      label: 'Security',
      collapsed: true,
      items: [
        'security/overview',
        'security/white-paper',
        'security/threat-model',
        'security/controls',
        'security/production-hardening-checklist',
        'security/least-privilege-tokens',
        'security/api-mediated-access',
        'security/process-isolation',
        'security/security-fixes',
        'security/responsible-disclosure',
      ],
    },
    'troubleshooting',
    'changelog',
  ],
};

export default sidebars;
